# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Gravatar
version:      0.01
version_from: lib/Template/Plugin/Gravatar.pm
installdirs:  site
requires:
    Carp:                          0
    Digest::MD5:                   0
    Test::More:                    0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
